services:
      api_helper:
        class: AppBundle\Services\APIHelper

      blog_extension:
        class: AppBundle\Twig\Extension\BlogExtension
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: twig.extension }